// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import FlashMessageController from './flash_message_controller';
import MenuController from './menu_controller';
import ThemeController from './theme_controller';

application.register('flash-message', FlashMessageController);
application.register('menu', MenuController);
application.register('theme', ThemeController);
